  name: Debug assemble jre package

on: workflow_dispatch

permissions:
  contents: write

jobs:
  assemble-package:
    strategy:
      matrix:
        include:
          - arch: "armel"
          - arch: "armhf"
    env:
      ARCH: ${{ matrix.arch }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Downloading jre
        run: |
          wget -nv https://github.com/vmnaumov/openjdk-6-armel/releases/download/jre1.0.1/jre-6-${{ env.ARCH }}.zip \
            -O jre.zip
          unzip jre.zip

      - name: Create package
        run: |    
          mv jre openjdk-6-jre

      - name: Compress
        run: |    
          zip -r openjdk-6-jre-${{ env.ARCH }}.zip openjdk-6-jre

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCH }}
          path: openjre-6-jre-${{ env.ARCH }}.zip

  release:
    needs: [ assemble-package ]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts

      - name: tree
        run: tree
